source 'https://rubygems.org'

gem 'bundle'
gem 'sinatra'
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'
gem 'sinatra-support'
gem 'sass'
gem 'compass'
gem 'haml'
gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'selenium-webdriver'
gem 'rake'
gem 'mongo'
gem 'bson_ext'
gem 'shotgun'